# Generated by Django 5.1.7 on 2025-03-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_pets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='pet_notes',
            field=models.TextField(blank=True, help_text="Notes about customer's pets"),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='animal_type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('FISH', 'Fish'), ('SMALL_ANIMAL', 'Small Animal'), ('REPTILE', 'Reptile'), ('ALL', 'All Animals')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Pet Food'), ('SUPPLIES', 'Pet Supplies'), ('ACCESSORIES', 'Pet Accessories'), ('MEDICINE', 'Pet Medicine'), ('HYGIENE', 'Pet Hygiene Products')], default='SUPPLIES', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='loyalty_points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit Card'), ('DEBIT', 'Debit Card'), ('PIX', 'PIX'), ('TRANSFER', 'Bank Transfer')], max_length=50),
        ),
    ]
